### ISSUE TITLE
Any plans to make it work on Julia v0.6?

### ISSUE THREAD

**Issue by juliohm** [Algocircle/YStockData.jl#1]
What is the challenge in migrating the API to Julia v0.6? Is there any other package where development is happening? Is YStockData.jl maintained?

**Comment by juliohm** [comment]
Just saw the other efforts in MarketData.jl and MarketTechnicals.jl, I am assuming research is taking place there now. Closing this.

**Comment by aviks** [comment]
Well, I wasn't sure if it makes sense to maintain this package any more, given that access to the Yahoo data seems uncertain these days.

**Comment by juliohm** [comment]
Very true, I just found this out: https://github.com/c0redumb/yahoo_quote_download

Is there any alternative source where we can query the same historical data? Does Google provide similar service? I couldn't find it online so far with my searches. I see that MarketData.jl provides a fred() data source, not sure what the difference is though.

**Comment by aviks** [comment]
`fred()` is economic data, i believe, not stock data afaik. Quandl.jl might be your best best at the moment. Free stock data is getting rarer and rarer.

**Comment by juliohm** [comment]
I joined the game too late then. First time trying to do algorithmic trading :disappointed:
